/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCreate.java
 *
 * Created on Aug 7, 2017, 2:50:47 PM
 */
package com.guestbook.app;

import java.awt.Toolkit;

/**
 *
 * @author 3rd Year Account
 */
public class FrmCreate extends javax.swing.JFrame {

    /** Creates new form FrmCreate */
    public FrmCreate() {
        setIcon();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncreate = new javax.swing.JButton();
        createcontact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createname = new javax.swing.JTextField();
        createid = new javax.swing.JTextField();
        creategender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        getContentPane().add(btncreate);
        btncreate.setBounds(120, 220, 150, 23);
        getContentPane().add(createcontact);
        createcontact.setBounds(248, 84, 122, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 127, 32, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(112, 58, 45, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Create");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 11, 70, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 58, 12, 15);
        getContentPane().add(createname);
        createname.setBounds(10, 148, 87, 20);
        getContentPane().add(createid);
        createid.setBounds(10, 84, 59, 20);
        getContentPane().add(creategender);
        creategender.setBounds(112, 84, 79, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(112, 127, 34, 15);
        getContentPane().add(createemail);
        createemail.setBounds(112, 148, 108, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("CONTACTNO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(248, 58, 72, 15);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 7.0.1\\Luna_Guestbook_080717\\src\\com\\guestbook\\app\\alliance.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, -10, 400, 290);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-338)/2, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
             if(SQLite.openDB()){
            String id = this.createid.getText();
            String name = this.createname.getText();
            String gender = this.creategender.getText();
            String email = this.createemail.getText();
            String contact = this.createcontact.getText();
            String values = id + "," + "'" + name + "'" +"," +"'"+gender+"'"+ ","+"'"+email+"'" +","+contact ;
            if(SQLite.create("guestbook", values)){
                javax.swing.JOptionPane.showMessageDialog(null, "New Guest has been created!");
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!");
            }
            SQLite.closeDB();
        }
}//GEN-LAST:event_btncreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmCreate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JTextField createcontact;
    private javax.swing.JTextField createemail;
    private javax.swing.JTextField creategender;
    private javax.swing.JTextField createid;
    private javax.swing.JTextField createname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
}
